# Generated by Django 5.2.6 on 2025-09-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('length', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'curses',
            },
        ),
        migrations.CreateModel(
            name='Lectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('curses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.curses')),
            ],
            options={
                'db_table': 'Lectors',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('curses', models.ManyToManyField(to='first.curses')),
                ('lectors', models.ManyToManyField(to='first.lectors')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
